POST http://localhost:8000/echos/v1 HTTP/1.1
content-type: application/json

{
    "username": "ibnu_basalamah",
    "email": "ibnubasalamah@yahoo.com",
    "referrance": null,
    "firstname": "ibnu",
    "lastname": "basalamah",
    "password": "pwsd_12345",
    "gender": "MALE"
}

######

POST http://localhost:8000/echos/v2 HTTP/1.1
content-type: application/json

{
    "username_email": "ibnubasalamah@yahoo.com",
    "password": "pwsd_12345"
}


#######

GET http://localhost:8000/events/v1 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ik1XUFZJWlBNWjQiLCJpbWFnZUlkIjpudWxsLCJmaXJzdG5hbWUiOiJpYm51IiwibGFzdG5hbWUiOiJiYXNhbGFtYWgiLCJ1c2VybmFtZSI6ImlibnVfYmFzYWxhbWFoIiwiZW1haWwiOiJpYm51YmFzYWxhbWFoQHlhaG9vLmNvbSIsImJpcnRoIjpudWxsLCJnZW5kZXIiOiJNQUxFIiwiYWRkcmVzcyI6bnVsbCwicmVmZXJyYWwiOiJJTkFQLVJSSU4iLCJyZWZlcnJhbmNlIjpudWxsLCJwb2ludCI6MCwicGhvbmVOdW1iZXIiOm51bGwsImV4cFBvaW50IjpudWxsLCJpbWFnZSI6bnVsbCwiUHJvbW90b3IiOlt7ImlkIjoiWkRPV0xKU0UwWCIsInByb21vdG9yTmFtZSI6ImlibnUgY29ycCIsInByb21vdG9yRGVzY3JpcHRpb24iOiJqYXNhIHdlYiIsInByb21vdG9ySW1hZ2UiOm51bGwsImJhbGFuY2UiOiIwIn1dLCJpYXQiOjE3MTc2MDgxMTksImV4cCI6MTcxNzYwOTAxOX0.Kpfr3viUwjLbiWZ-G6uI1e_lHXwiF85W9s8myE_XPUk


####

GET http://localhost:8000/events/v1/co8bnqcrmgV4bKJSrS9Cj HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ik1XUFZJWlBNWjQiLCJpbWFnZUlkIjpudWxsLCJmaXJzdG5hbWUiOiJpYm51IiwibGFzdG5hbWUiOiJiYXNhbGFtYWgiLCJ1c2VybmFtZSI6ImlibnVfYmFzYWxhbWFoIiwiZW1haWwiOiJpYm51YmFzYWxhbWFoQHlhaG9vLmNvbSIsImJpcnRoIjpudWxsLCJnZW5kZXIiOiJNQUxFIiwiYWRkcmVzcyI6bnVsbCwicmVmZXJyYWwiOiJJTkFQLVJSSU4iLCJyZWZlcnJhbmNlIjpudWxsLCJwb2ludCI6MCwicGhvbmVOdW1iZXIiOm51bGwsImV4cFBvaW50IjpudWxsLCJpbWFnZSI6bnVsbCwiUHJvbW90b3IiOlt7ImlkIjoiWkRPV0xKU0UwWCIsInByb21vdG9yTmFtZSI6ImlibnUgY29ycCIsInByb21vdG9yRGVzY3JpcHRpb24iOiJqYXNhIHdlYiIsInByb21vdG9ySW1hZ2UiOm51bGwsImJhbGFuY2UiOiIwIn1dLCJpYXQiOjE3MTc2MDgxMTksImV4cCI6MTcxNzYwOTAxOX0.Kpfr3viUwjLbiWZ-G6uI1e_lHXwiF85W9s8myE_XPUk

####
POST http://localhost:8000/events/v1 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ik1XUFZJWlBNWjQiLCJpbWFnZUlkIjpudWxsLCJmaXJzdG5hbWUiOiJpYm51IiwibGFzdG5hbWUiOiJiYXNhbGFtYWgiLCJ1c2VybmFtZSI6ImlibnVfYmFzYWxhbWFoIiwiZW1haWwiOiJpYm51YmFzYWxhbWFoQHlhaG9vLmNvbSIsImJpcnRoIjpudWxsLCJnZW5kZXIiOiJNQUxFIiwiYWRkcmVzcyI6bnVsbCwicmVmZXJyYWwiOiJJTkFQLVJSSU4iLCJyZWZlcnJhbmNlIjpudWxsLCJwb2ludCI6MCwicGhvbmVOdW1iZXIiOm51bGwsImV4cFBvaW50IjpudWxsLCJpbWFnZSI6bnVsbCwiUHJvbW90b3IiOlt7ImlkIjoiWkRPV0xKU0UwWCIsInByb21vdG9yTmFtZSI6ImlibnUgY29ycCIsInByb21vdG9yRGVzY3JpcHRpb24iOiJqYXNhIHdlYiIsInByb21vdG9ySW1hZ2UiOm51bGwsImJhbGFuY2UiOiIwIn1dLCJpYXQiOjE3MTc2MDYyNjEsImV4cCI6MTcxNzYwNzE2MX0.7h8FlHw2h8y7fxA2gqBWEi9oJouRPpio4qcloLku3xM

{
      "slug": "tokopedia.com",
      "title": "patty",
      "price": 50000,
      "priceVip": 100000,
      "startAt": "2025-04-01T18:00:00.000Z",
      "endAt": "2025-04-04T18:00:00.000Z",
      "location": "Indonesia",
      "description": "",
      "city": "Depok",
      "venueType": "INDOOR",
      "category": ""
}

##### 

POST http://localhost:8000/promotors/v1 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ik1XUFZJWlBNWjQiLCJpbWFnZUlkIjpudWxsLCJmaXJzdG5hbWUiOiJpYm51IiwibGFzdG5hbWUiOiJiYXNhbGFtYWgiLCJ1c2VybmFtZSI6ImlibnVfYmFzYWxhbWFoIiwiZW1haWwiOiJpYm51YmFzYWxhbWFoQHlhaG9vLmNvbSIsImJpcnRoIjpudWxsLCJnZW5kZXIiOiJNQUxFIiwiYWRkcmVzcyI6bnVsbCwicmVmZXJyYWwiOiJJTkFQLVJSSU4iLCJyZWZlcnJhbmNlIjpudWxsLCJwb2ludCI6MCwicGhvbmVOdW1iZXIiOm51bGwsImV4cFBvaW50IjpudWxsLCJpbWFnZSI6bnVsbCwiUHJvbW90b3IiOlt7ImlkIjoiWkRPV0xKU0UwWCIsInByb21vdG9yTmFtZSI6ImlibnUgY29ycCIsInByb21vdG9yRGVzY3JpcHRpb24iOiJqYXNhIHdlYiIsInByb21vdG9ySW1hZ2UiOm51bGwsImJhbGFuY2UiOiIwIn1dLCJpYXQiOjE3MTc2MDIxOTcsImV4cCI6MTcxNzYwMzA5N30.npSLeMzGLyuPnQ4dFChn_NladejOVo6W80PNiqR5Q0k

{
     "promotorName": "ibnu corp", 
     "promotorDescription": "jasa web"
}

####

GET http://localhost:8000/ HTTP/1.1


    # Promotor: {
    #     id: string
    #     promotorName: string
    #     promotorDescription: string | null
    #     promotorImage: { name: string | null } | null
    #     balance: Decimal
    # }