import "dotenv/config";

const PORT = process.env.PORT || 8001;
const SECRET_KEY_ACCESS = process.env.SECRET_KEY_ACCESS || "";
const SECRET_KEY_REFRESH = process.env.SECRET_KEY_REFRESH || "";
const BASE_URL = process.env.BASE_URL || "http://localhost:3000";
const NODEMAILER_USER = process.env.NODEMAILER_USER || "";
const NODEMAILER_PASSWORD = process.env.NODEMAILER_PASSWORD || "";
const SECRET_KEY_FORGET_PASSWORD = process.env.SECRET_KEY_FORGET_PASSWORD || "";
const SECRET_KEY_FORGET_PASSWORD_ACCESS =
  process.env.SECRET_KEY_FORGET_PASSWORD_ACCESS || "";

export {
  PORT,
  SECRET_KEY_ACCESS,
  SECRET_KEY_REFRESH,
  BASE_URL,
  NODEMAILER_PASSWORD,
  NODEMAILER_USER,
  SECRET_KEY_FORGET_PASSWORD_ACCESS,
  SECRET_KEY_FORGET_PASSWORD,
};
